###########################################
#
#        BlockPartyReborn v1.0.0
#       by Maximilian1021 and l4zs
#
###########################################


#####################
#					#
#		MySQL		#
#	Konfiguration	#
#					#
#####################

use: false
host: localhost
port: 3306
database: Minecraft_Blockparty
username: Minecraft
password: 12345


#####################
#					#
#	  Bungeecord    #
#	            	#
#####################
bungeecord: false
restartAfterGame: true
sendToHubBeforRestart: false


