name: BlockpartyReborn
description: Blockparty
api-version: 1.16
authors:
  - Maximilian1021
  - l4zs
main: me.maximilian1021.blockpartyreborn.BlockPartyReborn
version: 1.0.0

commands:
  blockparty:
    aliases:
      - bp
      - blockparty